#==================== Tomcat Setting =====================#
server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  port: 9081
#==================== spring Setting =====================#
spring:
  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xduojdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      max-active: 50
      min-idle: 10
      initial-size: 10
      max-wait: 10
      default-auto-commit: true
  http:
    encoding:
      charset: UTF-8
  profiles:
    active: prod

mybatis:
  config-location: classpath:mybatis.config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.oj.judge.entity

#==================== logging Setting =====================#
#logging:
#  config: classpath:logback.xml


#==================== project Setting =====================#
project:
  debug: true
file:
  upload:
    path: /home/oj/static/images
    relative: /home/oj/static/images/**
  server:
    http:
      prefix: http://localhost:8081/
    dir: /home/oj/static/
    image:
      dir: ${file.server.dir}/image
    testcase:
      dir: ${file.server.dir}/testcase
    type:
      image: jpg,png,bmp,gif,jpeg,psd,svg
      doc: doc,docx,xls,xlsx,txt,in,out
#====================rocketMQ Setting =====================#
rocketmq:
  nameserver: 150.223.209.209:9876
  topic: ojcode
  consumer:
    group: judgeConsumerGroup
    max-thread: 20
    min-thread: 10